version: '3.8'

services:
  cat-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: cat-service:latest
    container_name: cat-service
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx512m
    entrypoint: [ "java", "-jar", "/app/src-1.0-SNAPSHOT.jar" ]
    networks:
      - microservice-network
networks:
  microservice-network:
    driver: bridge
    external: true