version: '3.8'

services:
  owner-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: owner-service:latest
    container_name: owner-service
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx512m
    entrypoint: [ "java", "-jar", "/app/src-1.0-SNAPSHOT.jar" ]
    networks:
      - postgres-network
  postgres:
    image: registry.gitlab.com/dalibo/postgresql_anonymizer
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres-network
networks:
  postgres-network:
    driver: bridge

volumes:
  postgres-data: